11/02/2022 01:50:06 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:06 AM Could not ingest a total of 0.
11/02/2022 01:50:06 AM Process ingest_data_for_one_station('USC00110072.txt',) Took 0.9607 seconds
11/02/2022 01:50:07 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:07 AM Could not ingest a total of 0.
11/02/2022 01:50:07 AM Process ingest_data_for_one_station('USC00110187.txt',) Took 1.1051 seconds
11/02/2022 01:50:09 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:09 AM Could not ingest a total of 0.
11/02/2022 01:50:09 AM Process ingest_data_for_one_station('USC00110338.txt',) Took 1.1075 seconds
11/02/2022 01:50:10 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:10 AM Could not ingest a total of 0.
11/02/2022 01:50:10 AM Process ingest_data_for_one_station('USC00111280.txt',) Took 0.9500 seconds
11/02/2022 01:50:11 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:11 AM Could not ingest a total of 0.
11/02/2022 01:50:11 AM Process ingest_data_for_one_station('USC00111436.txt',) Took 1.1827 seconds
11/02/2022 01:50:12 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:12 AM Could not ingest a total of 0.
11/02/2022 01:50:12 AM Process ingest_data_for_one_station('USC00112140.txt',) Took 0.9673 seconds
11/02/2022 01:50:13 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:13 AM Could not ingest a total of 0.
11/02/2022 01:50:13 AM Process ingest_data_for_one_station('USC00112193.txt',) Took 1.2434 seconds
11/02/2022 01:50:14 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:14 AM Could not ingest a total of 0.
11/02/2022 01:50:14 AM Process ingest_data_for_one_station('USC00112348.txt',) Took 1.1026 seconds
11/02/2022 01:50:15 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:15 AM Could not ingest a total of 0.
11/02/2022 01:50:15 AM Process ingest_data_for_one_station('USC00112483.txt',) Took 1.0831 seconds
11/02/2022 01:50:16 AM Successfully ingested a total of 10 out of 10 records.
11/02/2022 01:50:16 AM Could not ingest a total of 0.
11/02/2022 01:50:16 AM Process ingest_data_for_one_station('USC00113335.txt',) Took 1.0535 seconds
11/02/2022 01:50:19 AM Successfully ingested a total of 30 out of 30 records.
11/02/2022 01:50:19 AM Could not ingest a total of 0.
11/02/2022 01:50:19 AM Process ingest_data_for_one_crop('US_corn_grain_yield.txt',) Took 3.0236 seconds
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.19.0.2:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:config.flask_and_database:Exception on /api/weather [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/views/app.py", line 18, in get_weather
    return jsonify(Weather.query.first())
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Weather is not JSON serializable
INFO:werkzeug:172.19.0.1 - - [02/Nov/2022 12:38:38] "[35m[1mGET /api/weather HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.19.0.2:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:config.flask_and_database:Exception on /api/weather [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/views/app.py", line 17, in get_weather
    return jsonify(Weather.query.first())
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Weather is not JSON serializable
INFO:werkzeug:172.19.0.1 - - [02/Nov/2022 12:39:53] "[35m[1mGET /api/weather HTTP/1.1[0m" 500 -
ERROR:config.flask_and_database:Exception on /api/weather [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/views/app.py", line 17, in get_weather
    return jsonify(Weather.query.first())
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Weather is not JSON serializable
INFO:werkzeug:172.19.0.1 - - [02/Nov/2022 12:40:27] "[35m[1mGET /api/weather HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.19.0.2:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.19.0.2:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:config.flask_and_database:Exception on /api/weather [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/views/app.py", line 17, in get_weather
    return jsonify(Weather.query.first())
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Weather is not JSON serializable
INFO:werkzeug:172.19.0.1 - - [02/Nov/2022 12:42:06] "[35m[1mGET /api/weather HTTP/1.1[0m" 500 -
